language: generic

dist: xenial
addons:
  snaps:
    - name: hugo

jobs:
  include:
    - stage: test
      script: echo first
    - # stage name not required, will continue to use `test`
      script: echo second
    - stage: deploy
      script: echo final
