language: generic

dist: xenial
addons:
  snaps:
    - name: hugo
    - name: aws-cli
      confinement: classic # or devmode
      channel: latest
    - name: go

jobs:
  include:
    - stage: test
      script: echo first
    - # stage name not required, will continue to use `test`
      script: echo second
    - stage: extra
      dist: bionic
      script: echo hi
    - stage: deploy
      git:
        clone: false
      script: echo final
      rvm: 
         - 2.3
      addons:
        snaps: 
         - hugo
         - aws-cli
