language: node_js

node_js:
  - '8'

env:
  global:
    - INSTALL_FRONTEND=false
  matrix:
    include:
      stage: test
        - TASK=lint
        - TASK=test:agent
        - TASK=test:finance
        - TASK=test:survey
        - TASK=test:token-manager
        - TASK=test:token-manager:app INSTALL_FRONTEND=true
        - TASK=test:vault
        - TASK=test:voting
        - TASK=test:payroll
        - TASK=test:shared
    stage:  coverage
      - TASK=coverage:agent
      - TASK=coverage:finance
      - TASK=coverage:survey
      - TASK=coverage:token-manager
      - TASK=coverage:vault
      - TASK=coverage:voting
      - TASK=coverage:payroll
    stage: allowed failures
      allow_failures:
        - env: TASK=coverage:agent
        - env: TASK=coverage:finance
        - env: TASK=coverage:payroll
install:
  - echo true
before_script:
  - echo Hi
script:
  - echo bye
